haproxy:
  image: tutum/haproxy
  ports:
    - "80:80"
  links:
    - web

web:
  build: .
  restart: always
  links:
    - mongo
  environment:
    - NODE_ENV
    - USER
    - PASS

mongo:
  image: mongo
